class ExplosiveBarrelBetter : ExplosiveBarrel replaces ExplosiveBarrel
{
    States
    {
        Death:
        BEXP A 3;
        BEXP B 4 ;
        BEXP C 5 Bright;
        BEXP D 5 Bright;
        BRXP B 0 Bright 
        {
        A_NoGravity();
        Radius_Quake (2,17,0,16,0);
        A_Scream();

        A_SpawnDebris("BarrelDebris", False, 3.1, 1.2); 
        A_SpawnDebris("BarrelDebris", False, 3.1, 1.2); 
        A_SpawnDebris("BarrelDebris", False, 3.1, 1.2); 
        A_SpawnDebris("BarrelDebris", False, 3.1, 1.2); 
        A_SpawnItemEX("BarrelBase");
        }
        BRXP B 0 Bright A_SetTranslucent(0.5, 1);
        BRXP ABCDEFGHIJ 2 Bright A_Explode(256, 120, 1);
        BRXP K 2 Bright ;
        BRXP L 2 BRIGHT;
        Stop;
    }
}

class BarrelDebris : LimbGib
{
    Default
    {
        BounceSound "";
    }
    States
    {
        Spawn:
        TNT1 A 0 NoDelay A_Jump(256, "Gib1", "Gib2", "Gib3","Gib4");
        Gib1:
        BEDB A 0;
        Goto SpawnLoop;
        Gib2:
        BEDB B 0;
        Goto SpawnLoop;
        Gib3:
        BEDB C 0;
        Goto SpawnLoop;
        Gib4:
        BEDB D 0;
        Goto SpawnLoop;
        Death:
        "####" "#" 0;
		"####" "#" 1;
		"####" "#" -1;
        Stop;
    }
}

class BarrelBase : Actor
{
    States
    {
        Spawn:
        BEDB E -1;
        Stop;
    }
}